In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split


In [8]:
data=pd.read_csv("C:/Users/SHIVAM/Desktop/Datasets/Sample5 - Brest Cancer.csv")

In [10]:
data.head(5)

Clump Thickness  Cell Size  Cell Shape  Marginal Adhesion  \
0                5          4           3                  1   
1                9          1           2                  6   
2               10          4           7                  2   
3                6         10          10                 10   
4                1          1           1                  1   

   Single Epithelial Cell Size  Bare Nuclei  Bland Chromatin  Normal Nucleoli  \
0                            2            1                2                3   
1                            4           10                7                7   
2                            2            8                6                1   
3                            8           10                7               10   
4                            2            5                5                1   

   Mitoses  Cancer  
0        1       1  
1        2       0  
2        1       0  
3        7       0  
4        1       1

In [13]:
X=data.iloc[:,0:9].values
Y=data.iloc[:,9].values

In [14]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [24]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_test

array([[-0.14360508, -0.69501655, -0.73879769, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       [-0.49880526, -0.04423891, -0.40248832, ..., -0.1749909 ,
         0.71433152, -0.32721154],
       [-0.49880526, -0.69501655, -0.06617895, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       ...,
       [-0.14360508, -0.69501655, -0.73879769, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       [ 1.63239582,  1.25731637,  1.27905854, ...,  1.45534096,
         1.70435958,  0.86828682],
       [-1.20920562, -0.69501655, -0.73879769, ..., -0.99015683,
        -0.6057059 , -0.32721154]])

In [17]:
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [20]:
X_test

array([[-0.14360508, -0.69501655, -0.73879769, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       [-0.49880526, -0.04423891, -0.40248832, ..., -0.1749909 ,
         0.71433152, -0.32721154],
       [-0.49880526, -0.69501655, -0.06617895, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       ...,
       [-0.14360508, -0.69501655, -0.73879769, ..., -0.58257386,
        -0.6057059 , -0.32721154],
       [ 1.63239582,  1.25731637,  1.27905854, ...,  1.45534096,
         1.70435958,  0.86828682],
       [-1.20920562, -0.69501655, -0.73879769, ..., -0.99015683,
        -0.6057059 , -0.32721154]])

In [47]:
classifier=KNeighborsClassifier(n_neighbors=20,p=1,metric='minkowski')

In [48]:
classifier.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=20, p=1,
           weights='uniform')

In [49]:
Y_pred=classifier.predict(X_test)

In [56]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score


In [51]:
cm=confusion_matrix(Y_pred,Y_test)

In [52]:
cm

array([[47,  1],
       [ 3, 89]], dtype=int64)

In [53]:
f1_score(Y_pred,Y_test)

0.978021978021978

In [57]:
accuracy_score(Y_pred,Y_test)

0.9714285714285714

In [62]:
X_test[0:][0]

array([-0.14360508, -0.69501655, -0.73879769, -0.62264311, -0.5454362 ,
       -0.68234296, -0.58257386, -0.6057059 , -0.32721154])